#+TITLE: ByteBack
#+STARTUP: noindent

ByteBack is a tool for specifying bytecode programs and for converting them into the Boogie intermediate verification language.

** Dependencies

In order to verify programs using ByteBack the following dependencies need to be installed separately:
+ [[https://github.com/Z3Prover/z3][Z3]] solver 4.10.2+
+ [[https://github.com/boogie-org/boogie][boogie]] 2.15.0+

** Building

To build the project use the following command:
#+begin_src sh
	gradlew install
#+end_src

This command will build the .jar archive of the core program ~byteback-core~ in
[[./byteback-core/build/libs/byteback-core.jar]],
and for ~byteback-annotations~ (BBLib) in
[[./byteback-annotations/build/libs/byteback-annotations.jar]].
It is possible to call ~byteback-core~ by using the execution script, which will be located in
[[./byteback-core/install/byteback-core/bin/byteback-core]].

** Using ByteBack core

~byteback-core~ is a converter for Java bytecode into the Boogie intermediate verification language.

The ~byteback-core~ executable can be invoked with the following options:
#+begin_src sh
	byteback-core -cp {classpath...} -c {target class...} -o {output Boogie file...}
#+end_src

- classpath :: The ~-cp~ option declares a classpath to be analyzed by ByteBack. This option can be repeated to specify multiple classpaths.

- starting class :: The ~-c~ option declares the fully qualified name of the class from which the analysis will start (i.e. the classes from which ByteBack will start the conversion). This option can be repeated to declare multiple starting classes. By including a single class, ByteBack will also recursively perform the conversion of any eventual class referenced by that class, excluding standard library classes.

- output file :: Finally, the ~-o~ option will correspond to the path to the output Boogie file. If this option is absent the Boogie program will be printed to stdout.

After generating the output Boogie program it can be verified using the ~boogie~ verification tool.

** Using ByteBack annotations

The ByteBack annotations library (BBLib) contains the necessary annotations and static methods used to specify bytecode programs.

In order to convert the annotated code, ~byteback-annotations~ must be included in the classpath used by ~byteback-core~.

** Running the Tests

Most of the tests performed by ByteBack are system tests that use ~byteback-core~ on the classes located in the [[./byteback-test][byteback-test]] subprojects.
These tests requires the following additional pypi dependencies (also listed at [[./byteback-test/requirements.txt]]):
+ [[https://llvm.org/docs/CommandGuide/lit.html][lit]] 15.0.0
+ [[https://llvm.org/docs/CommandGuide/FileCheck.html][filecheck]] 0.0.22

To run the system tests execute the ~system~ gradle task as follows:
#+begin_src sh
	gradlew system
#+end_src

It is also possible to specify a single test by using the ~TARGET~ property:
#+begin_src sh
	gradlew system -PTARGET={Path to the test file (.java or .scala)}
#+end_src
