#+TITLE: TODO
#+AUTHOR: Marco Paganoni

* Project structure
** DONE Main modules
The initial structure for the project will include two main modules: ~jayproof-annotations~ and ~jayproof-core~. The first module will be a library providing all the necessary annotations construct to annotate the projects. These will be provided to the main application ~jayproof-core~.

** DONE Testing structure
Unit tests should be provided for both the ~annotations~ and the ~core~ module. To test the integration between these two modules additional integration tests will be added to the ~core~ module, which will operate on the compiled classes of the modules contained in the ~jayproof-dummy~ directory.

The structure of ~jayproof-dummy~ as for now will be divided based on the target version of the language features that will be supported by the ~core~ module. For instance  ~jayproof-dummy:jdk1.8~ will be a test module compiled for version ~1.8~. As the necessity of supporting features present in other versions of the JDK will emerge, more similar submodules will be added.

